### PR TITLE
added swedish locale

### PR DESCRIPTION
**Pull request by krippz**
Hi,
I did the Swedish translation. 
Cheers

### CODE REVIEW

**Comment by johnkors** [comment]
Takk! Har du en skrivefeil på ResourceOwnerFlowLoginFailure, eller det rett?

**Comment by krippz** [comment]
Ah sorry, I'll fix it :)

**Comment by johnkors** [comment]
Also, could you add it to the list of supported translations?

https://github.com/krippz/IdentityServer3.Contrib.Localization/blob/master/source/IdentityServer3.Localization/Internals/LocalizationServiceFactory.cs#L20

I forgot to add that to the contributing section in the readme :/

**Comment by johnkors** [comment]
thanks! Don't worry about the failed build. It will fix itself with the next idsrv upgrade coming next week. (1.1.0). There's a bug in idsrv that's fixed in the idsrv dev branch that I'm waiting for.

**Comment by krippz** [comment]
Ah ok, I just saw that the tests fails because of the missing sv-SE attributes.
Sorry about that, i switched machines, now on Mac and xunit is not working :(

**Pull request merged**
