### PR TITLE
original resource files

### PR DESCRIPTION
**Pull request by gustavoruscitto**
Original resource files copied from Thinktecture.IdentityServer3.
Not sure if all the keys are needed, I see just a subset for the other translations.

### CODE REVIEW

**Comment by johnkors** [comment]
Thanks!

**Comment by gustavoruscitto** [comment]
you're welcome!

**Comment by johnkors** [comment]
I´ll look into the missing ids. Did you get it from the idsrv master-branch? or dev? I know they added a couple of new stuff to be translated in dev.

https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/7cf06b3c3c8eb50c50f66ac1c0be012c8ff0b35d

**Comment by gustavoruscitto** [comment]
I took them from master branch... Let me check dev.

**Comment by gustavoruscitto** [comment]
@johnkors I found the same in dev. There are a couple of extra sentences (invalid_request in Messages and a few more in Events)

**Comment by johnkors** [comment]
Ah, I guess they were just missing from the T4 template containing all the public ids then. Thanks for checking.

**Pull request merged**
