### PR TITLE
ru-RU (Russian) localization added

### PR DESCRIPTION
**Pull request by kirychenkav**

### CODE REVIEW

**Comment by johnkors** [comment]
Hi! Thanks alot! Could you rebase off master? There are some conflicts with the latest source.

**Comment by kirychenkav** [comment]
Sorry for many commits. It was my the first rebase. And it was a bad idea to use Git Gui... Tell me if I made any mistakes.

**Comment by johnkors** [comment]
Yeah, it does not look as a successful rebase. The result should be only your commits in this PR. Maybe open a new one based off master.

**Comment by kirychenkav** [comment]
I opened a new PR (https://github.com/johnkors/IdentityServer3.Contrib.Localization/pull/32)

**Pull request closed without merging**
